# Generated by Django 5.0.1 on 2024-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20240204_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rent_price',
            field=models.IntegerField(null=True),
        ),
    ]
