# Generated by Django 5.0.1 on 2024-02-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_apartment_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
