# Generated by Django 3.2.7 on 2024-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_remove_photo_apart_media_remove_video_apart_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
