# Generated by Django 3.2.7 on 2024-02-02 14:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0002_auto_20240202_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('rent_price', models.IntegerField()),
                ('start_rent_date', models.DateField()),
                ('contract_duration', models.DurationField(editable=False)),
                ('notify_me', models.BooleanField(default=True)),
                ('contract_photo', models.ImageField(upload_to='')),
                ('notes', models.TextField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
            ],
        ),
    ]
