# Generated by Django 3.2.7 on 2024-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0003_auto_20240212_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingdates',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
