# Generated by Django 3.2.7 on 2024-02-04 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcontract',
            name='contract_duration',
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='duration_in_months',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rentcontract',
            name='end_rent_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='contract_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
