# Generated by Django 3.2.7 on 2024-02-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0005_remove_rentcontract_end_rent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingdates',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='rent_price',
            field=models.IntegerField(null=True),
        ),
    ]
