# Generated by Django 3.2.7 on 2024-02-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0007_alter_rentcontract_start_rent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingdates',
            name='date',
            field=models.DateField(),
        ),
    ]
