# Generated by Django 3.2.7 on 2024-02-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_contract', '0008_alter_payingdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='start_rent_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
