# Generated by Django 3.2.7 on 2024-02-04 16:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Please Enter The Phone-Country First Like The following:                                    +201032479669', max_length=128, region=None, unique=True),
        ),
    ]
